# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
